Template
tsohleDev/Portfolio pull request #1
Opened 2022-10-28 07:51 UTC by tsohleDev

Initialize the repository with a templte

2022-10-28 08:45 UTC, Debas-31 requested changes
> ## Hi @tsohleDev  :wave: 
# Status : INVALID REQUEST :stop_sign: :stop_sign: :stop_sign: 

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, 

- [x] The Pull Request shouldn't have a descriptive title telling what changes are inside and a summary describing introduced changes in more detail.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 10:26 UTC, tsohleDev commented
I  really don't understand, what is it that should be written in a pull request?

2022-10-28 10:37 UTC, mckent05 reviewed
Hi  @tsohleDev,

# STATUS: INVALID REQUEST ❌ ❌  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive PR title and summary. 
Please edit your PR summary by clicking on the three dots in the image attached below and selecting the 'edit' button 👍 👍 

<img width="639" alt="pr edit" src="https://user-images.githubusercontent.com/73607512/198567973-0f1d5cc4-ee3e-4fb1-8be6-af02333fca20.PNG">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 12:13 UTC, andgarzonmal requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 Hi @tsohleDev ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 

### 💯  Highlights 💯
- Your gitHub flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️

### ♻️ Request changes ♻️

- [x] _Check the comments under the review._
___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-28 12:13 UTC, andgarzonmal commented on index.html
> +    </header>
- [x] Kyndly follow the template for the bobile version,  the mobile version for your template only contains the hamburguer menu in the header. 

### Figma design 
![image](https://user-images.githubusercontent.com/95243996/198579420-1eaed3b0-b57e-4da0-a8a1-94482bdbcf74.png)

### Your design 
![image](https://user-images.githubusercontent.com/95243996/198580115-5b7c5132-a535-4bb0-a473-157882f323b4.png)

2022-10-28 12:13 UTC, andgarzonmal commented on index.html
> +    </header>
[Optional] As you have already worked on the links thar are displayed on the desktop version is not required to remove what you have done, but for now you will have to set the display as none for those links, I recommendo you doing something similar to this.

![image](https://user-images.githubusercontent.com/95243996/198581309-3a529007-3f96-4904-8aab-fdbe350bafb2.png)

You will have to set the nav_links class as none first so on your css you an put this 

![image](https://user-images.githubusercontent.com/95243996/198581685-2b6a12a1-6e88-4333-83d6-654f8fc34ef0.png)

2022-10-28 12:13 UTC, andgarzonmal commented on style.css
> +
- [ ]  Kyndly follow the figma design as much as you can, as you can see in the mobile version of figma there is a background image on the top left corner, plese add it to your project. Take into account that if an image is not part of the content (aesthetic reasons) use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.

### Figma design
![image](https://user-images.githubusercontent.com/95243996/198582465-b71593b6-eaeb-47fc-8d81-d179cab70d75.png)

### Your project 

![image](https://user-images.githubusercontent.com/95243996/198582833-ac5e492a-6535-4019-add0-be17f5d23396.png)

2022-10-28 12:13 UTC, andgarzonmal commented on style.css
> +.bio {
- [ ] kyndly use the correct fonts and colors, 

### Figma design 
![image](https://user-images.githubusercontent.com/95243996/198583375-c2fd9980-8f8a-4119-b0ab-c5952d7b4ab7.png)

### your project 

![image](https://user-images.githubusercontent.com/95243996/198583764-83b8ee55-0111-4f89-827f-22a9915bd215.png)

2022-10-28 14:38 UTC, tsohleDev commented
Making a mobile website for my portfolio using a figma template

2022-10-28 15:38 UTC, BertrandConxy requested changes
Hi @tsohleDev, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- No linter errors
- correct flow is used
- good improvement based on the previous reviewer's suggestions
- good PR


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 15:38 UTC, BertrandConxy commented on style.css
> +  font-family: sans-serif;
- [x] As suggested by the previous reviewer, please use the correct font family in this paragraph and the button below it 😃.
**Your design**
![image](https://user-images.githubusercontent.com/90222110/198676645-f25653af-2955-49c9-8287-da445776f91b.png)
**Given design**
![image](https://user-images.githubusercontent.com/90222110/198676727-c6fb94f7-a675-49cf-9864-dd26e82a95fa.png)

**HINT** The font family is called `Poppins` sans-serif

2022-10-29 03:11 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️   

## Hi @tsohleDev 👋,

You've done well implementing some of the requested changes 👏 , but there are still some which haven't been addressed yet.

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ No linter errors.
✔️ Good code structure.
✔️ Nice job following some of the previous requests!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 03:11 UTC, Gopxfs commented on style.css
> +}
As requested by the previous reviewer, kindly use the same font as the one displayed on Figma 😉:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/198796588-06a88bc1-d9ba-4833-a2c0-3e35b3351f14.png)  | ![image](https://user-images.githubusercontent.com/42799579/198796465-33771f43-05c9-4469-a997-d26c45243fd2.png)  |

2022-10-29 04:46 UTC, TuyishimireEric approved these changes
# Status: APPROVED  :+1: :+1:  
## Hi  @tsohleDev    :hand: 

Thank you for Implementing the requested changes from the previous code reviewer :clap: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All tests are passing ✔️ 
- Correct use of GitFlow ✔️
- Professional PR ✔️
- Professional commit  ✔️

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)


## Optional suggestions
_NA_

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 04:56 UTC, merged